services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: sahishnukumaar
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: resume_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      OUTPUT_DIR: /output
    volumes:
      - /Users/sahishnukumaar/Desktop/NUS-Study-Materials/Resume:/output
volumes:
  postgres_data:
