services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: sahishnukumaar
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: resume_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
